package:
  name: l2winddir
  version: {{ environ.get('GIT_DESCRIBE_TAG', 0)}}

source:
  # path: ../.conda
  git_url: https://github.com/jean2262/l2winddir.git
  git_rev: HEAD

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.10,<3.12
    - setuptools >=64.0
    - setuptools_scm >=6.0
    - pip
  host:
    - python >=3.10,<3.12
    - grdtiler
    - hydra-zen
    - omegaconf
    - pytorch 
    - pytorch-cuda=11.8
    - torchaudio
    - torchvision
    - lightning
    - einops
    - opencv
  run:
    - python >=3.10,<3.12
    - grdtiler
    - hydra-zen
    - omegaconf
    - pytorch 
    - pytorch-cuda=11.8
    - torchaudio
    - torchvision
    - lightning
    - einops
    - opencv

channels:
  - pytorch
  - nvidia
  - conda-forge
  - oceanscope

about:
  home: https://github.com/jean2262/l2winddir.git
  license: MIT
  summary: "A package for predicting wind direction on SAR images."

extra:
  recipe-maintainers:
    - jean2262