[build-system]
requires = ["setuptools>=64.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "999"

[project.scripts]
l2winddir_predict = "l2winddir.safe_predict:main"
